import 'package:pharmacy_app/models/category_model.dart';
import 'package:pharmacy_app/models/product_model.dart';

final List<CategoryModel> categories = [
  CategoryModel('Thuốc', 'assets/images/pill.svg'),
  CategoryModel('Thực phẩm chức năng', 'assets/images/apple.svg'),
  CategoryModel('Dụng cụ y tế', 'assets/images/stethoscope.svg'),
  CategoryModel('Mẹ & bé', 'assets/images/baby.svg'),
  CategoryModel('Chăm sóc sức khỏe', 'assets/images/heart.svg'),
];

final List<ProductModel> products = [
  ProductModel(
    category: categories[0],
    name: 'Paracetamol 500mg',
    price: 15000,
    image: 'https://picsum.photos/id/1011/400/400',
    description: 'Thuốc giảm đau, hạ sốt thông dụng, an toàn cho người lớn và trẻ em.',
    usage: 'Uống 1 viên sau ăn khi có triệu chứng đau hoặc sốt. Không quá 4g/ngày.',
    ingredients: 'Paracetamol 500mg, tá dược vừa đủ.',
  ),
  ProductModel(
    category: categories[0],
    name: 'Aspirin 81mg',
    price: 18000,
    image: 'https://picsum.photos/id/1012/400/400',
    description: 'Thuốc giúp ngăn ngừa kết tập tiểu cầu, hỗ trợ phòng ngừa bệnh tim mạch.',
    usage: 'Uống 1 viên/ngày sau bữa ăn, dùng theo chỉ dẫn bác sĩ.',
    ingredients: 'Aspirin 81mg, cellulose, tinh bột ngô.',
  ),
  ProductModel(
    category: categories[0],
    name: 'Amoxicillin 500mg',
    price: 24000,
    image: 'https://picsum.photos/id/1013/400/400',
    description: 'Kháng sinh phổ rộng, điều trị các nhiễm khuẩn đường hô hấp, tiết niệu.',
    usage: 'Uống 1 viên x 3 lần/ngày, liên tục từ 7–10 ngày.',
    ingredients: 'Amoxicillin trihydrate 500mg, tá dược vừa đủ.',
  ),
  ProductModel(
    category: categories[1],
    name: 'Vitamin C 1000mg',
    price: 55000,
    image: 'https://picsum.photos/id/1014/400/400',
    description: 'Bổ sung vitamin C giúp tăng sức đề kháng và làm đẹp da.',
    usage: 'Uống 1 viên mỗi ngày sau bữa ăn sáng.',
    ingredients: 'Vitamin C 1000mg, chiết xuất cam, hương liệu tự nhiên.',
  ),
  ProductModel(
    category: categories[1],
    name: 'Omega 3 Fish Oil',
    price: 120000,
    image: 'https://picsum.photos/id/1015/400/400',
    description: 'Bổ sung Omega 3 giúp tăng cường trí nhớ và tốt cho tim mạch.',
    usage: 'Uống 1–2 viên/ngày sau bữa ăn chính.',
    ingredients: 'Dầu cá tinh khiết, EPA, DHA, vitamin E.',
  ),
  ProductModel(
    category: categories[1],
    name: 'Collagen Dạng Nước',
    price: 89000,
    image: 'https://picsum.photos/id/1016/400/400',
    description: 'Giúp da săn chắc, mịn màng, hỗ trợ giảm nếp nhăn.',
    usage: 'Uống 1 chai mỗi ngày trước khi ngủ để đạt hiệu quả tối ưu.',
    ingredients: 'Collagen peptide, vitamin C, chiết xuất nho, nước tinh khiết.',
  ),
  ProductModel(
    category: categories[2],
    name: 'Máy Đo Huyết Áp Omron',
    price: 850000,
    image: 'https://picsum.photos/id/1018/400/400',
    description: 'Thiết bị theo dõi huyết áp chính xác, tiện lợi cho gia đình.',
    usage: 'Quấn băng đo quanh cánh tay và nhấn nút khởi động.',
    ingredients: 'Thiết bị điện tử, vòng bít, màn hình LCD, pin AA.',
  ),
  ProductModel(
    category: categories[2],
    name: 'Nhiệt Kế Điện Tử Microlife',
    price: 120000,
    image: 'https://picsum.photos/id/1020/400/400',
    description: 'Dụng cụ đo thân nhiệt nhanh và chính xác cho mọi lứa tuổi.',
    usage: 'Đặt đầu đo dưới lưỡi hoặc nách, chờ 30 giây để có kết quả.',
    ingredients: 'Nhựa ABS, đầu cảm biến nhiệt, pin lithium.',
  ),
  ProductModel(
    category: categories[2],
    name: 'Băng Gạc Y Tế',
    price: 25000,
    image: 'https://picsum.photos/id/1024/400/400',
    description: 'Dùng để cầm máu, bảo vệ vết thương tránh nhiễm khuẩn.',
    usage: 'Làm sạch vết thương trước khi băng. Thay băng mỗi 12 giờ.',
    ingredients: 'Sợi cotton tiệt trùng, vải không dệt.',
  ),
  ProductModel(
    category: categories[3],
    name: 'Sữa Dành Cho Bé Friso Gold',
    price: 520000,
    image: 'https://picsum.photos/id/1025/400/400',
    description: 'Sữa công thức giúp trẻ tăng cân, phát triển não bộ và hệ tiêu hoá khỏe mạnh.',
    usage: 'Pha 4 muỗng sữa với 180ml nước ấm, dùng 2–3 lần/ngày.',
    ingredients: 'Sữa bột, DHA, canxi, vitamin D, kẽm.',
  ),
  ProductModel(
    category: categories[3],
    name: 'Tã Dán Huggies M',
    price: 260000,
    image: 'https://picsum.photos/id/1027/400/400',
    description: 'Tã dán siêu thấm hút, êm ái cho làn da nhạy cảm của bé.',
    usage: 'Thay tã sau 4 tiếng hoặc khi ướt để đảm bảo vệ sinh cho bé.',
    ingredients: 'Bông tự nhiên, polymer thấm hút, vải không dệt.',
  ),
  ProductModel(
    category: categories[3],
    name: 'Khăn Ướt Cho Bé Bobby',
    price: 35000,
    image: 'https://picsum.photos/id/1029/400/400',
    description: 'Khăn ướt mềm mại, không cồn, an toàn cho da bé.',
    usage: 'Dùng để lau tay, mặt hoặc khi thay tã cho bé.',
    ingredients: 'Nước tinh khiết, chiết xuất lô hội, vitamin E.',
  ),
  ProductModel(
    category: categories[4],
    name: 'Khẩu Trang 3D Mask',
    price: 75000,
    image: 'https://picsum.photos/id/1031/400/400',
    description: 'Khẩu trang lọc bụi mịn và vi khuẩn hiệu quả đến 99%.',
    usage: 'Đeo che kín mũi miệng, thay mới mỗi 3–4 giờ sử dụng.',
    ingredients: 'Vải không dệt, lớp lọc than hoạt tính.',
  ),
  ProductModel(
    category: categories[4],
    name: 'Dung Dịch Rửa Tay Lifebuoy',
    price: 45000,
    image: 'https://picsum.photos/id/1033/400/400',
    description: 'Rửa tay kháng khuẩn mạnh mẽ, giúp bảo vệ khỏi vi trùng gây bệnh.',
    usage: 'Lấy lượng vừa đủ, xoa đều tay trong 30 giây rồi rửa sạch bằng nước.',
    ingredients: 'Alcohol 70%, glycerin, tinh dầu bạc hà, hương liệu.',
  ),
  ProductModel(
    category: categories[4],
    name: 'Nước Súc Miệng Listerine',
    price: 89000,
    image: 'https://picsum.photos/id/1035/400/400',
    description: 'Giúp làm sạch khoang miệng, ngăn ngừa hôi miệng và vi khuẩn.',
    usage: 'Súc miệng 30 giây với 20ml dung dịch, 2 lần/ngày.',
    ingredients: 'Menthol, thymol, eucalyptol, methyl salicylate.',
  ),
];

